version: 2
jobs:
  build:
    docker:
      - image: lachlanevenson/docker-make
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build kubectl container
          command: |
            GIT_BRANCH=$CIRCLE_BRANCH make docker_build
      - run:
          name: Test kubectl container
          command: |
            GIT_BRANCH=$CIRCLE_BRANCH make test
      - run:
          name: Publish kubectl container
          branches:
            only:
              - master
              - /v.*/
          command: |
            echo $DOCKER_PASS | base64 -d > ${HOME}/docker_pass
            docker login -u $DOCKER_USER -p "$(cat ${HOME}/docker_pass)"
            GIT_BRANCH=$CIRCLE_BRANCH make docker_push
